server:
  port: 8001
  servlet:
    context-path: /
    encoding:
      charset: utf-8


spring:
  application:
    name: gateway  
  cloud:
    gateway:
      routes:
      - id: demo
        uri: lb://demo
        predicates:
          - Path=/demo/**
        filters:
          - StripPrefix=1
          - PrefixPath=/
      - id: demo-sentinel
        uri: lb://demo
        predicates:
          - Path=/demo-sentinel/**
        filters:
          - StripPrefix=1
          - PrefixPath=/
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8081
      eager: true
    
  


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/


