server:
  port: 8011
  servlet:
    context-path: /
    encoding:
      charset: utf-8

spring:
  application:
    name: demo


management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
