spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
swagger:
  enable: true

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false